#ifndef __ULANG_COMPILER_ERRNO_H
#define __ULANG_COMPILER_ERRNO_H

#define ULANG_SYNT_ERR_BASE 1000

#define ULANG_SYNT_ERR_UNEXCEPT_TOK     (ULANG_SYNT_ERR_BASE + 2)
#define ULANG_SYNT_ERR_EXCEPTED_PRIMARY (ULANG_SYNT_ERR_BASE + 3)

#endif
