#ifndef __ULANG_COMPILER_ERRNO_H
#define __ULANG_COMPILER_ERRNO_H

#define ULANG_SYNT_ERR_BASE 1000
#define ULANG_SYNT_WARN_BASE 3000

#define ULANG_SYNT_ERR_UNEXCEPT_TOK         (ULANG_SYNT_ERR_BASE + 2)
#define ULANG_SYNT_ERR_EXCEPTED_PRIMARY     (ULANG_SYNT_ERR_BASE + 3)
#define ULANG_SYNT_ERR_TYPE_DETERMINE_FAIL  (ULANG_SYNT_ERR_BASE + 4)
#define ULANG_SYNT_ERR_VAR_UNDEFINED        (ULANG_SYNT_ERR_BASE + 5)
#define ULANG_SYNT_ERR_EXCEPTED_EXPR        (ULANG_SYNT_ERR_BASE + 6)
#define ULANG_SYNT_ERR_FN_REDEFINE          (ULANG_SYNT_ERR_BASE + 11)
#define ULANG_SYNT_ERR_FN_NOT_FN            (ULANG_SYNT_ERR_BASE + 12)

#define ULANG_SYNT_WARN_TYPES_SIGN_DIFF     (ULANG_SYNT_WARN_BASE + 2)
#define ULANG_SYNT_WARN_TYPES_SIZE_DIFF     (ULANG_SYNT_WARN_BASE + 3)
#define ULANG_SYNT_WARN_DIVISION_ZERO       (ULANG_SYNT_WARN_BASE + 5)
#define ULANG_SYNT_WARN_FN_NO_BODY          (ULANG_SYNT_ERR_BASE + 11)

#endif
